import jsPDF from "jspdf";

export const generateCertificatePDF = (unitateInvatamant: any, nr: any, data: any, elev: any, clasa: any, anuScolarIncep: any, anuScolarSfrst: any, serversteLa: any) => {
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "pt",
        format: "A4",
    });

    const marginLeft = 40;
    let y = 50;

    doc.setFillColor(...[20, 43, 94]);
    doc.rect(0, 0, doc.internal.pageSize.width, 85, 'F');
    doc.setTextColor(...[255, 255, 255]);

    doc.setFont("Times", "Normal");
    doc.setFontSize(12);
    doc.text("Unitatea de invatamant", marginLeft, y);
    doc.text(`Nr. ${nr}`, 380, y);
    y += 20;
    doc.text(`${unitateInvatamant}`, marginLeft, y);
    doc.text(`Data ${data}`, 380, y);

    y += 50;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(20);
    doc.setFont("Times", "Bold");
    doc.text("ADEVERINTA", doc.internal.pageSize.getWidth() / 2, y, { align: "center" });

    y += 40;
    doc.setFontSize(12);
    doc.setFont("Times", "Normal");

    doc.text(`        Elev(a) ${elev} este inscris(a) in clasa (anul) ${clasa} in anul scolar ${anuScolarIncep} - ${anuScolarSfrst}. Adeverinta`, marginLeft, y);
    y += 20;
    doc.text(`se elibereaza de unitatea de invatamant pentru a-i servi la: ${serversteLa}`, marginLeft, y);

    y += 50;
    doc.text("DIRECTOR,", marginLeft, y);
    doc.text("Secretar,", doc.internal.pageSize.getWidth() - marginLeft - 60, y);


    y += 90;
    doc.setDrawColor(...[37, 99, 235]);
    doc.setLineWidth(0.5);
    doc.line(marginLeft, y - 5, doc.internal.pageSize.width - 55, y - 5);

    doc.setTextColor(...[107, 114, 128]);
    doc.setFontSize(10);
    y += 10;
    doc.text('Generated by SmartClass © 2024', marginLeft, y);
    doc.text(`Page 1 of 1`, doc.internal.pageSize.width - 55, y, { align: 'right' });


    doc.save(`adeverinta_${elev}.pdf`);
};
