import jsPDF from "jspdf";

export const generateRaportAbsentePDF = (
    unitateInvatamant: string,
    data: string,
    nume: string,
    prenume: string,
    lunaAn: string,
    absente: any,
) => {
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "pt",
        format: "A4",
    });

    const marginLeft = 40;
    let y = 40;

    doc.setFillColor(...[20, 43, 94]);
    doc.rect(0, 0, doc.internal.pageSize.width, 85, 'F');
    doc.setTextColor(...[255, 255, 255]);

    // Antet stânga și dreapta
    doc.setFont("Times", "Normal");
    doc.setFontSize(12);
    doc.text("Unitatea de invatamant", marginLeft, y);
    doc.text(`${unitateInvatamant}`, marginLeft, y + 12);
    doc.text(`Data: ${data}`, 400, y);

    // Titlu
    y += 70;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("Times", "Bold");
    doc.text("Raport absente", doc.internal.pageSize.getWidth() / 2, y, { align: "center" });
    doc.setFontSize(12);
    doc.text(`- ${new Date(lunaAn + "-01").toLocaleString("ro-RO", { month: "long", year: "numeric" })} -`,
        doc.internal.pageSize.getWidth() / 2, y + 16, { align: "center" });

    // Nume și prenume
    y += 50;
    doc.setFont("Times", "Normal");
    doc.setFontSize(12);
    doc.text(`Nume: ${nume}`, marginLeft, y);
    doc.text(`Prenume: ${prenume}`, marginLeft, y + 18);

    y += 30;

    // Linii tabel
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);

    y += 30;
    const dataRowHeight = 20;
    const colWidths = [310, 190]; // lățimile celor două coloane
    const colX = [marginLeft, marginLeft + colWidths[0]];
    const pageHeight = doc.internal.pageSize.height;
    const bottomMargin = 60;

    let absenteMotivate = 0;
    for (let i = 0; i < absente?.length; i++) {
        if (y + dataRowHeight > pageHeight - bottomMargin) {
            doc.addPage();
            y = 40;
        }
        if (absente[i].excused) {
            ++absenteMotivate;
        }
        doc.rect(colX[0], y, colWidths[0], dataRowHeight);
        doc.rect(colX[1], y, colWidths[1], dataRowHeight);
        doc.text(
            absente[i].date.toLocaleDateString("ro-RO").replace(/\//g, "."),
            colX[0] + 5,
            y + 14
        );
        doc.text(absente[i].excused ? "motivata" : "nemotivata", colX[1] + 5, y + 14);
        y += dataRowHeight;
    }

    const totalsHeight = 60;
    if (y + totalsHeight > pageHeight - bottomMargin) { // if there isn't space for totals
        doc.addPage();
        y = 40;
    }

    // Totaluri
    y += 20;
    doc.setFontSize(12);
    doc.text("Total absente motivate:", marginLeft, y);
    doc.text(`${absenteMotivate}`, marginLeft + 120, y);
    doc.text("Total absente nemotivate:", marginLeft, y + 18);
    doc.text(`${absente.length - absenteMotivate}`, marginLeft + 130, y + 18);
    doc.text("Total absente:", marginLeft, y + 36);
    doc.text(`${absente.length}`, marginLeft + 75, y + 36);

    const footerY = doc.internal.pageSize.height - 15;

    doc.setDrawColor(...[37, 99, 235]);
    doc.setLineWidth(0.5);
    doc.line(20, footerY - 5, doc.internal.pageSize.width - 20, footerY - 5);

    doc.setTextColor(...[107, 114, 128]);
    doc.setFontSize(8);
    doc.text('Generated by SmartClass © 2024', 20, footerY + 5);

    doc.save(`raport_absente_${nume}_${prenume}.pdf`);
};
